services:
  - type: web
    name: video-site
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: VIDEO_1_TITLE
        sync: false
      - key: VIDEO_1_URL
        sync: false
      - key: VIDEO_2_TITLE
        sync: false
      - key: VIDEO_2_URL
        sync: false
      - key: VIDEO_3_TITLE
        sync: false
      - key: VIDEO_3_URL
        sync: false
      - key: VIDEO_4_TITLE
        sync: false
      - key: VIDEO_4_URL
        sync: false
      - key: VIDEO_5_TITLE
        sync: false
      - key: VIDEO_5_URL
        sync: false
      - key: VIDEO_6_TITLE
        sync: false
      - key: VIDEO_6_URL
        sync: false
      - key: VIDEO_7_TITLE
        sync: false
      - key: VIDEO_7_URL
        sync: false
      - key: VIDEO_8_TITLE
        sync: false
      - key: VIDEO_8_URL
        sync: false
      - key: VIDEO_9_TITLE
        sync: false
      - key: VIDEO_9_URL
        sync: false
      - key: VIDEO_10_TITLE
        sync: false
      - key: VIDEO_10_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: video-site-db
          property: connectionString

databases:
  - name: video-site-db
    plan: free